### PR TITLE
Move some modules (vdm, verdict-bundle-parent)

### PR DESCRIPTION
**Pull request by tuxji**
1) Copy com.ge.research.osate.verdict.vdm from tools/verdict to
tools/verdict-data-model.

2) Change com.ge.research.osate.verdict.vdm (we still need it) to
simply bundle vdm and its transitive dependencies into an Eclipse
bundle that the other verdict bundles can use.

3) Change tools/verdict-back-ends/verdict-bundle-parent projects to
use verdict-data-model's new Maven coordinates instead of
com.ge.research.osate.verdict.vdm's Maven coordinates.

4) Move tools/verdict-back-ends/verdict-bundle-parent projects up one
directory to tools/verdict-back-ends and remove empty
verdict-bundle-parent directory.

5) Update build instructions in tools/verdict/back-ends/README.md.

If you have an Eclipse workspace, you will need to remove and reimport
all the Verdict projects in order to update your workspace.  Don't
forget to run `mvn clean install -Dtycho.localArtifacts=ignore` in the
tools directory before reimporting the projects.

### CODE REVIEW

**Comment by baoluomeng** [comment]
With this VDM move, if we create a completely new project that depends on VDM, what does user need to do?

**Comment by baoluomeng** [comment]
> With this VDM move, if we create a completely new project that depends on VDM, what does user need to do?

Assuming the user is creating a Maven project and he wants to use VDM.

**Comment by baoluomeng** [comment]
Also, I noticed that you list all the modules (originally in the verdict-bundle-parent) in the verdict-back-end repo. I misunderstood what you said on Slack. I still think it is better to group original modules in the bundle project inside one Maven project since we use the entire project as a standalone jar.

**Comment by tuxji** [comment]
After this VDM move, if you want to create a Maven project and use VDM in the project, you will put a single dependency in your pom.xml:

```xml
            <dependency>
                <groupId>com.ge.verdict</groupId>
                <artifactId>verdict-data-model</artifactId>
            </dependency>
```

The instructions will be different if you are creating an Eclipse plugin project; then you need to put a Require-Bundle: com.ge.research.osate.verdict.vdm in your MANIFEST.MF.

**Comment by tuxji** [comment]
Some advantages to moving the projects are:

1. The verdict-bundle-parent directory wasn't a very good name.  I like verdict-back-ends better.
2. Since Maven ignores the STEM and OCaml projects, we benefit nothing from having the verdict-bundle-parent directory.
3. We won't have to cd one level deeper in the terminal or see two nested "project of projects" projects in our Eclipse project (both verdict-back-ends and verdict-bundle-parent).
4. Logically and in truth, the verdict-bundle app invokes all the back-end programs, not just the Java programs.  It just runs the non-Java programs in subprocesses while it calls the Java programs directly.
5. There's only one README to read (verdict-back-ends/README.md) for back-end build instructions now, not two READMEs.
6. Both Vidhya and Daniel liked the idea and said okay already.

**Comment by baoluomeng** [comment]
> Some advantages to moving the projects are:
> 
> 1. The verdict-bundle-parent directory wasn't a very good name.  I like verdict-back-ends better.
> 2. Since Maven ignores the STEM and OCaml projects, we benefit nothing from having the verdict-bundle-parent directory.
> 3. We won't have to cd one level deeper in the terminal or see two nested "project of projects" projects in our Eclipse project (both verdict-back-ends and verdict-bundle-parent).
> 4. Logically and in truth, the verdict-bundle app invokes all the back-end programs, not just the Java programs.  It just runs the non-Java programs in subprocesses while it calls the Java programs directly.
> 5. There's only one README to read (verdict-back-ends/README.md) for back-end build instructions now, not two READMEs.
> 6. Both Vidhya and Daniel liked the idea and said okay already.

1. I have no objection against the naming change from verdict-bundle-parent to verdict-back-ends. 
2. The way I see the the modules inside original verdict-bundle-parent is that they are all written in Java and should belong to the same Java Maven project. Now it seems like they are mixed with STEM and OCaml projects, which make the repo look really unclean. 
3. To me the entire bundle project is the middle layer of the VERDICT project. The real back-ends are Soteria++ and Kind2.
4. Conceptually, the entire bundle project is a standalone Java Maven project. Each of other projects (aadl2iml, Soteria++) is a standalone OCaml project. STEM is just one of the inputs to the bundle project. If we import the "original bundle project" from verdict-back-ends repo into Eclipse, would the OCaml project be imported into Eclipse as well? If yes, we should avoid doing that since those OCaml projects are not part of bundle project.
5. I agree that one single README is cleaner. We can still keep that one at that level but need to change the wording a bit saying all the java maven modules are under the bundle project (or you can give a more informative and meaningful name), and show the build instruction for the bundle at that level as you already did.

I am sorry about this confusion. I know it would cost you extra efforts to make the changes. But I think logically the Java Maven project modules should reside separate from the OCaml projects.

**Comment by tuxji** [comment]
Do you want to consider moving the STEM and OCaml projects instead of the Java Maven projects?  That would minimize the rework time since I won't have to change as many pom files.  However, I have a hard time thinking of logical names for their new locations that would be an improvement over either 1) keeping all the back-end projects in the same directory as I propose, or 2) making verdict-bundle the middle layer of the VERDICT project as you want.

To answer your question about Eclipse, you were importing the entire tools directory into Eclipse already.  If you expand your tools project in your Eclipse workspace, you will see verdict and verdict-back-ends directories even though they also exist as their own projects in the workspace.  Likewise, if you expand your verdict-back-ends project, you will see STEM, aadl2iml, and soteria_pp directories as well as verdict-bundle-parent even though your workspace doesn't have separate projects for them, only for verdict-bundle-parent.  That's what still would happen if all the back-end projects were in the same directory (verdict-back-ends).  You would see verdict-back-ends as a project and the rest of the Java Maven projects as projects but you would never see STEM, aadl2iml, or soteria_pp unless you expanded your verdict-back-ends project.

If you still want me to go back to the structure we had before, I will make the following two changes:

- Change `tools/verdict-back-ends/verdict-bundle-parent` to `tools/verdict-back-ends/verdict-bundle`
- Change `tools/verdict-back-ends/verdict-bundle-parent/verdict-bundle` to `tools/verdict-back-ends/verdict-bundle/verdict-bundle-app`

You will see tools, verdict, verdict-back-ends, and verdict-bundle as module projects in your workspace (they will contain only directories, not source files) and the rest of the Java Maven projects as source projects (they will have Java files).

**Comment by baoluomeng** [comment]
I prefer the following suggestion to group all the bundle modules inside one Java Maven project as you proposed below.  The rest remains unchanged. You can still keep the README inside the verdict-back-ends repo. 

> If you still want me to go back to the structure we had before, I will make the following two changes:
> 
> * Change `tools/verdict-back-ends/verdict-bundle-parent` to `tools/verdict-back-ends/verdict-bundle`
> * Change `tools/verdict-back-ends/verdict-bundle-parent/verdict-bundle` to `tools/verdict-back-ends/verdict-bundle/verdict-bundle-app`

**Comment by tuxji** [comment]
FYI, I haven't been able to fully test the changes because I've been having some DNS problems inside my WSL build environment after switching from WSL1 to WSL2.  I'll have to merge the pull request after the checks pass, let CI update the docker image and update site, and then use them to test the changes.  Please help test the changes if you can too.

**Comment by tuxji** [comment]
Actually I also have a Cygwin build environment so I've built the plugin and tested it in my OSATE now.  soteria_pp crashes for some reason but otherwise the translators seem to work.  I'll merge the PR and let others test too.

**Pull request merged**
